Task/user auth
uw-it-aca/compass pull request #36
Opened 2022-06-03 23:03 UTC by charlon

2022-06-03 23:05 UTC, charlon commented
I'll leave this as a DRAFT for now - as some authorization details are still being worked out. Per our discussion in the Compass check-in... we still need to decide the best way to pass user authorization down to the Vue components. Also worth discussing - do we use the default Django 403 response or use a static page outside of Django.

2022-06-03 23:11 UTC, devights approved these changes

2022-06-03 23:53 UTC, abztrakt approved these changes

2022-06-06 22:18 UTC, nick-falco requested changes

2022-06-06 22:18 UTC, nick-falco commented on compass_vue/helpers/utils.js
> +  return { role: "Super" };
Yeah I think this is where we would do map the local "Role" class variable to the role defined in the server's response context

2022-06-06 22:31 UTC, nick-falco approved these changes
We'll eventually want a link to Support for "Admin" and "Support" users, but we can leave that out until we add the uw supporttools app. I'm not sure if that will make MVP or not

2022-06-06 22:44 UTC, merged